const express=require("express")
const bodyparser=require("body-parser")
const app=express()
const User=require("./models/UserModel")
app.use(bodyparser.json())
const cors=require("cors")
const signup=require("./routes/signUp")
const signin=require("./routes/signIn")
const find=require("./routes/getUserbyArea")
const login=require("./routes/Login")
const update=require("./routes/updatePassword")
app.use(cors())
app.use("/",signup)
app.use("/",signin)
app.use("/",find)
app.use("/",login)
app.use("/",update)
app.all("*",(req,res)=>res.status(404).send("404 Error"))
app.listen(3001,()=>console.log("server started"))