const express=require("express")
const bodyparser=require("body-parser")
const app=express()
const User=require("./models/UserModel")
app.use(bodyparser.json())
const signup=require("./routes/signUp")
const signin=require("./routes/signIn")
const find=require("./routes/getUserbyArea")
app.use("/",signup)
app.use("/",signin)
app.use("/",find)
app.all("*",(req,res)=>res.status(404).send("404 Error"))
app.listen(3001,()=>console.log("server started"))